### ISSUE TITLE
Help testing against edge resque

### ISSUE THREAD

**Issue by steveklabnik** [ticktricktrack/resque-web_no_act#1]
Hey there! 

I'm gearing up to work on Resque 2.0, and I'd like to coordinate better with plugin authors to make sure stuff doesn't break.

I'd like to know a few things:
1. Can I do something to help get you testing against edge Resque?
2. Are you monkey-patching anything in Resque currently? Can 2.0 expose an API to help you not have to do that any more?
3. Do you need any help in bringing your plugin up-to-date with the latest Resque?

Thanks!

Related: https://github.com/defunkt/resque/issues/880

**Comment by ticktricktrack** [comment]
Sorry for not responding earlier. Since the resque repo has moved the 2.0 discussion seemed to have been deleted in the move. 
1. Happy for the help, but this is a super trivial gem, so it won't need much work.
2. No monkey patching at all. And no changes to resque whatsoever. This gem is a subclass to the resque server, just overriding server methods not to do anything!
3. I think I can manage, I'm quite interested in any Resque improvements anyways.

**Comment by steveklabnik** [comment]
Awesome! Yeah, it's at https://github.com/resque/resque/issues/880 now.

The big change for you and 2.0 is that resque-web 2.0 is in Rails.
